spring.application.name=TupperMania

# --- CONEXIÓN MONGODB ATLAS ---
# Reemplaza <PASSWORD> con tu contraseña real y <CLUSTER> con tu url (ej: cluster0.xyz.mongodb.net)
spring.mongodb.uri=mongodb+srv://admin:admin@tuppercluster.sfdh0pl.mongodb.net/?appName=TupperCluster
spring.mongodb.database=tuppermania_db

# --- LOGS (Vital para ver si conecta) ---
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# --- CONFIGURACIÓN GEMINI API ---
gemini.api.key=AIzaSyCVXu18LEb5yTm9lbmEydVVKNoU9mlFpJk
